name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Build Vue
      run: |
              export NODE_OPTIONS=--openssl-legacy-provider
              npm ci
              npm run build
              cd dist
              ln -s index.html 404.html
              if [ "none" !=  ci ]; then echo 'ci' > CNAME; fi
              git config --global user.email "$CI@example.com"
              git config --global user.name "FaultyPine"
              git init
              git add -A
              git commit -m 'deploy'
              git push -f https://FaultyPine:${{ secrets.GITHUB_TOKEN }}@github.com/FaultyPine/FaultyPine.github.io.git master:gh-pages
