name: 'Automatic build'
on:
  push:
    branches:
      - main

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
      - run: npm install
      - name: Building the project
      - run: bash deploy.sh