name: 'Automatic build'
on:
  push:
    branches:
      - main

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master
        run: npm install

      - name: Deploy
        run: bash deploy.sh